import {
  HEALTHCHECK_DEFAULTS,
  type AppDefinition,
  type SecretSource,
} from '@mediaplane/engine';

export const FACTS_START =
  '<!-- BEGIN GENERATED by "pnpm docs:generate" from app.ts. Do not edit. -->';
export const FACTS_END = '<!-- END GENERATED -->';

const code = (text: string) => `\`${text}\``;

const list = (values: readonly string[]) =>
  values.length === 0 ? 'nothing' : values.map(code).join(', ');

function ports(def: AppDefinition): string {
  if (def.ports.length === 0) return 'none';
  return def.ports
    .map((port) => {
      const where =
        port.publish === false
          ? 'inside the stack only'
          : port.hostEqualsContainer === undefined
            ? `published as \`network.bind\` says; \`apps.${def.id}.port\` moves the host port`
            : `published as \`network.bind\` says; \`apps.${def.id}.port\` moves the host and container port together (\`${port.hostEqualsContainer.env}\`)`;
      return `${String(port.container)}/${port.protocol ?? 'tcp'} (${port.name}), ${where}`;
    })
    .join('; ');
}

function volumes(def: AppDefinition): string {
  const { appdata, data } = def.volumes;
  const mounts = [
    ...(appdata === undefined
      ? []
      : [`${code(`<home>/appdata/${def.id}`)} → ${code(appdata)}`]),
    ...(data === undefined ? [] : [`the data folder (\`paths.data\`) → ${code(data)}`]),
  ];
  return mounts.length === 0 ? 'none' : mounts.join('; ');
}

function runsAs(def: AppDefinition): string {
  switch (def.runAs) {
    case 'puid-env':
      return "the stack's `user:`, through `PUID` and `PGID`";
    case 'user-directive':
      return "the stack's `user:`, through Compose's `user:`";
    case 'image-default':
      return "the image's own user";
    default: {
      const uid = def.runAs.slice('fixed:'.length);
      return `uid ${uid}, fixed by the image. Mediaplane gives \`<home>/appdata/${def.id}\` to ${uid}:${uid} before the app starts`;
    }
  }
}

function health(def: AppDefinition): string {
  if (def.health === 'none') return 'none: `up --wait` waits only for it to be running';
  if (def.health === 'image') return "the image's own";
  const { interval, timeout, retries } = HEALTHCHECK_DEFAULTS;
  const start = def.health.startPeriod ?? HEALTHCHECK_DEFAULTS.startPeriod;
  // Compose reads $$ as a literal $; show the command as the shell runs it.
  const test = def.health.test.slice(1).join(' ').replaceAll('$$', '$');
  return `${code(test)}, every ${interval} (timeout ${timeout}, ${String(retries)} retries, ${start} to start)`;
}

function api(def: AppDefinition): string {
  if (def.api === undefined) return 'none that Mediaplane calls';
  const { port, key } = def.api;
  const carried =
    key.scheme === 'bearer' ? 'as a Bearer token' : 'in the `X-Api-Key` header';
  return `on its ${code(port)} port, which Mediaplane reaches over the stack's wiring network, with ${code(key.secret)} ${carried}`;
}

/** What Mediaplane manages in the app, as override keys name it (spec §4.2, §6.3). */
function managed(def: AppDefinition): string {
  const resources = def.integration?.resources ?? [];
  if (resources.length === 0) return 'nothing yet';
  return resources
    .map((resource) => {
      const fields = resource.fields.map((field) =>
        code(`${def.id}.${resource.name}.${field}`),
      );
      const secrets = resource.secrets.map(code);
      return `${code(`${def.id}.${resource.name}`)}: ${[
        ...(fields.length === 0 ? [] : [`fields ${fields.join(', ')}`]),
        ...(secrets.length === 0
          ? []
          : [`the secret ${secrets.join(', ')}, checked and never shown`]),
      ].join('; ')}`;
    })
    .join('. ');
}

function secret(source: SecretSource): string {
  if ('generate' in source) {
    return source.generate === 'hex32'
      ? '32 random hex characters, generated once and kept in `state/secrets.json`'
      : '`qbt_` and 28 random letters and digits, generated once and kept in `state/secrets.json`';
  }
  if ('createdBy' in source) return 'created by the app during its first-run setup';
  return `yours, from \`${source.userProvided}\` in \`stack.yaml\``;
}

function secrets(def: AppDefinition): string {
  const entries = Object.entries(def.secrets)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([name, source]) => `${code(name)}: ${secret(source)}`);
  return entries.length === 0 ? 'none' : entries.join('; ');
}

function turnsOn(def: AppDefinition): string {
  const parsed = def.options?.safeParse({});
  const implied = def.implies?.(parsed?.success === true ? parsed.data : {}) ?? [];
  return implied.length === 0
    ? 'nothing'
    : `${implied.map(code).join(', ')}, with the default settings`;
}

/** The facts for one app, from its app.ts: one list item per setting, which wraps on a phone. */
export function renderFacts(def: AppDefinition): string {
  const facts: [string, string][] = [
    ['Image', code(`${def.image.repo}:${def.image.tag}`)],
    ['Digest', code(def.image.digest)],
    ['Architectures', def.arch.join(', ')],
    ['Ports', ports(def)],
    ['Volumes', volumes(def)],
    ['Runs as', runsAs(def)],
    ['Health check', health(def)],
    ['Secrets', secrets(def)],
    ['API', api(def)],
    ['Managed in the app', managed(def)],
    ['Needs', list(def.requires.map((r) => r.capability))],
    ['Provides', list(def.provides)],
    ['Also turns on', turnsOn(def)],
  ];
  return [
    FACTS_START,
    '',
    '## What Mediaplane sets',
    '',
    ...facts.map(([name, value]) => `- **${name}:** ${value}`),
    '',
    FACTS_END,
  ].join('\n');
}

/** `readme`, with its generated block replaced by the facts for `def`. */
export function withFacts(readme: string, def: AppDefinition, path: string): string {
  const start = readme.indexOf(FACTS_START);
  const end = readme.indexOf(FACTS_END);
  if (start < 0 || end < start) {
    throw new Error(
      `${path} needs the lines ${FACTS_START} and ${FACTS_END}, where the generated facts go`,
    );
  }
  return `${readme.slice(0, start)}${renderFacts(def)}${readme.slice(end + FACTS_END.length)}`;
}
