import {
  createProgram,
  defaultDeps,
  ENVIRONMENT,
  EXIT_CODES,
} from '../../packages/cli/src/run';
import { cell, prose } from './stack-reference';

type Program = ReturnType<typeof createProgram>;

const GENERATED =
  '<!-- Generated by "pnpm docs:generate" from packages/cli/src/run.ts. Do not edit. -->';

/** The CLI as a user sees it, with no environment: so the same on every machine. */
function program(): Program {
  const quiet = { stdout: () => undefined, stderr: () => undefined, env: {} };
  return createProgram(quiet, defaultDeps({}), () => undefined);
}

/** docs/reference/cli.md (spec §9), from the Commander program itself. */
export function renderCliReference(cli: Program = program()): string {
  const help = cli.createHelp();
  const lines = [
    '# CLI reference',
    '',
    GENERATED,
    '',
    'Every command takes `--json` for machine-readable output, and `--help` for this help. `mediaplane --version` prints the version.',
    '',
  ];
  for (const command of help.visibleCommands(cli)) {
    if (command.name() === 'help') continue;
    lines.push(
      `## \`mediaplane ${command.name()}\``,
      '',
      `${command.description()}.`,
      '',
      '```text',
      help.commandUsage(command),
      '```',
      '',
    );
    const args = help.visibleArguments(command);
    if (args.length > 0) {
      lines.push(
        '| Argument | Description |',
        '| --- | --- |',
        ...args.map(
          (arg) =>
            `| \`${help.argumentTerm(arg)}\` | ${cell(help.argumentDescription(arg))} |`,
        ),
        '',
      );
    }
    const options = help
      .visibleOptions(command)
      .filter((option) => option.long !== '--help');
    lines.push(
      '| Option | Description |',
      '| --- | --- |',
      ...options.map(
        (option) =>
          `| \`${help.optionTerm(option)}\` | ${cell(help.optionDescription(option))} |`,
      ),
      '',
      'Exit codes:',
      '',
      ...(EXIT_CODES[command.name()] ?? []).map((code) => `- ${code}`),
      '',
    );
  }
  // A list, not a table: the descriptions are long, and a table scrolls on a phone.
  lines.push(
    '## Environment variables',
    '',
    ...ENVIRONMENT.map(
      (variable) => `- \`${variable.name}\`: ${prose(variable.description)}`,
    ),
    '',
  );
  return lines.join('\n');
}
