import type { Catalog } from '@mediaplane/engine';

/** The parts of a JSON Schema the reference reads. */
export interface Schema {
  $id?: string;
  type?: string | string[];
  description?: string;
  default?: unknown;
  const?: unknown;
  enum?: unknown[];
  minimum?: number;
  maximum?: number;
  properties?: Record<string, Schema>;
  required?: string[];
  additionalProperties?: Schema | boolean;
  anyOf?: Schema[];
}

const GENERATED =
  '<!-- Generated by "pnpm docs:generate" from packages/engine/src/config/schema.ts and the catalog. Do not edit. -->';

/** { file } or { env }: shown as one type. */
function isSecretRef(schema: Schema): boolean {
  const keys = (schema.anyOf ?? []).map((option) =>
    Object.keys(option.properties ?? {}).join(),
  );
  return keys.length === 2 && keys.includes('file') && keys.includes('env');
}

/** "a", "a or b", "a, b or c". */
function orList(items: readonly string[]): string {
  return items.length < 2
    ? (items[0] ?? '')
    : `${items.slice(0, -1).join(', ')} or ${items.at(-1) ?? ''}`;
}

/** A field's type, in words. */
export function typeOf(schema: Schema): string {
  if (schema.const !== undefined) return `\`${JSON.stringify(schema.const)}\``;
  if (schema.enum !== undefined) {
    return orList(schema.enum.map((value) => `\`${String(value)}\``));
  }
  if (isSecretRef(schema)) return 'secret reference';
  const options = (schema.anyOf ?? []).filter((option) => option.type !== 'null');
  if (options.length > 0) return options.map(typeOf).join(' or ');
  const types = Array.isArray(schema.type) ? schema.type : [schema.type ?? 'any'];
  if (types.length > 1) return orList(types);
  const type = types[0] ?? 'any';
  if (type === 'integer') return integerRange(schema);
  if (type === 'object' && typeof schema.additionalProperties === 'object') {
    return `map of name → ${typeOf(schema.additionalProperties)}`;
  }
  return type;
}

function integerRange({ minimum, maximum }: Schema): string {
  if (
    minimum !== undefined &&
    maximum !== undefined &&
    maximum < Number.MAX_SAFE_INTEGER
  ) {
    return `integer, ${String(minimum)} to ${String(maximum)}`;
  }
  return minimum === undefined ? 'integer' : `integer, at least ${String(minimum)}`;
}

/** A string YAML reads as a string without quotes: a word, path or name. */
const PLAIN_STRING = /^[A-Za-z][\w./-]*$/;
/** Words some YAML parsers read as a boolean or null, so they are quoted. */
const YAML_WORDS = /^(true|false|null|yes|no|on|off|y|n)$/i;

/** A default as it would be written in stack.yaml: `lan`, `{ uid: 1000, gid: 1000 }`. */
export function yamlValue(value: unknown): string {
  if (Array.isArray(value)) {
    return value.length === 0 ? '[]' : `[${value.map(yamlValue).join(', ')}]`;
  }
  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value);
    if (entries.length === 0) return '{}';
    return `{ ${entries.map(([key, child]) => `${key}: ${yamlValue(child)}`).join(', ')} }`;
  }
  if (typeof value === 'string') {
    return PLAIN_STRING.test(value) && !YAML_WORDS.test(value)
      ? value
      : JSON.stringify(value);
  }
  return JSON.stringify(value);
}

/** One field's list item, and its fields' after it. Maps and secret references are one. */
function items(schema: Schema, prefix: string): string[] {
  const required = new Set(schema.required ?? []);
  return Object.entries(schema.properties ?? {}).flatMap(([name, child]) => {
    const field = prefix === '' ? name : `${prefix}.${name}`;
    const qualifier = required.has(name)
      ? '; required'
      : child.default === undefined
        ? ''
        : `; default \`${yamlValue(child.default)}\``;
    return [
      `- \`${field}\` (${typeOf(child)}${qualifier}): ${prose(child.description ?? '')}`,
      ...items(child, field),
    ];
  });
}

/**
 * Markdown text on one line, with "<" escaped outside code spans: GitHub reads `<app>` as
 * an HTML tag and drops it from the page. Inside a code span a backslash would show, and
 * `<home>` is safe. A backtick with no closing one opens no span.
 */
function prose(text: string): string {
  const parts = text.replaceAll('\n', ' ').split('`');
  return parts
    .map((part, index) =>
      index % 2 === 1 && index < parts.length - 1 ? part : part.replaceAll('<', '\\<'),
    )
    .join('`');
}

/** A Markdown table cell: as prose, with pipes escaped everywhere, code spans included. */
export const cell = (text: string) => prose(text).replaceAll('|', '\\|');

/** An app's entry under apps:, without its "or nothing" alternative. */
function entryOf(schema: Schema | undefined): Schema {
  return (schema?.anyOf ?? []).find((option) => option.type === 'object') ?? {};
}

/** docs/reference/stack-yaml.md (spec §9), from the published JSON Schema and the catalog. */
export function renderStackReference(schema: Schema, catalog: Catalog): string {
  const top = Object.fromEntries(
    Object.entries(schema.properties ?? {}).map(([name, child]): [string, Schema] => [
      name,
      // apps gets sections of its own below.
      name === 'apps' ? { ...child, properties: undefined } : child,
    ]),
  );
  const entries = schema.properties?.apps?.properties ?? {};
  const keysOf = (id: string) => Object.keys(entryOf(entries[id]).properties ?? {});
  const shared = catalog
    .map((def) => keysOf(def.id))
    .reduce((common, keys) => common.filter((key) => keys.includes(key)));
  const sharedSchema = entryOf(entries[catalog[0]?.id ?? '']);
  const sharedItems = items(
    {
      properties: Object.fromEntries(
        shared.map((key): [string, Schema] => [
          key,
          sharedSchema.properties?.[key] ?? {},
        ]),
      ),
    },
    'apps.<app>',
  );
  const ownItems = catalog.flatMap((def) => {
    const entry = entryOf(entries[def.id]);
    const own = Object.entries(entry.properties ?? {}).filter(
      ([key]) => !shared.includes(key),
    );
    return items({ properties: Object.fromEntries(own) }, `apps.${def.id}`);
  });
  return [
    '# `stack.yaml` reference',
    '',
    GENERATED,
    '',
    '`stack.yaml` describes the stack you want, and `mediaplane plan` and `apply` make the host match it. This page lists every field.',
    '',
    `Editors can check the file as you type against its [JSON Schema](stack.schema.json). \`mediaplane init\` writes this first line for you:`,
    '',
    '```yaml',
    `# yaml-language-server: $schema=${schema.$id ?? ''}`,
    '```',
    '',
    'A **secret reference** is `{ file: secrets/<name> }`, a file relative to the Mediaplane home, or `{ env: NAME }`, an environment variable. A secret itself never goes in `stack.yaml` ([ADR 0009](../adr/0009-no-secrets-in-stack-yaml.md)).',
    '',
    '## Fields',
    '',
    'Each field shows its type, then `required` or its default, if it has one.',
    '',
    ...items({ ...schema, properties: top }, ''),
    '',
    '## Settings every app takes',
    '',
    'Under `apps.<app>`, where `<app>` is one of the apps listed at the end of this page.',
    '',
    ...sharedItems,
    '',
    "## One app's own settings",
    '',
    ...ownItems,
    '',
    '## Apps',
    '',
    '| App | Id |',
    '| --- | --- |',
    ...catalog.map(
      (def) => `| [${def.name}](../../catalog/${def.id}/README.md) | \`${def.id}\` |`,
    ),
    '',
  ].join('\n');
}
