import { catalog } from '@mediaplane/catalog';
import { stackJsonSchema } from '@mediaplane/engine';
import { describe, expect, it } from 'vitest';
import { cell, renderStackReference, typeOf, type Schema } from './stack-reference';

const text = renderStackReference(stackJsonSchema(catalog), catalog);

describe('renderStackReference', () => {
  it('lists each field with its type, default and description', () => {
    expect(text).toContain('| `paths.data` | string | required | The data folder');
    expect(text).toContain(
      '| `network.bind` | one of `lan`, `localhost`, `all` | `"lan"` |',
    );
    expect(text).toContain(
      '| `admin.password` | secret reference |  | The admin password',
    );
    // Required once user: is given; user: itself has a default.
    expect(text).toContain(
      '| `user.uid` | integer, at least 0 | required | The user id. |',
    );
  });

  it("lists the settings every app takes once, and each app's own", () => {
    expect(text).toContain('| `apps.<app>.port` | integer, 1 to 65535 |  |');
    expect(text).toContain(
      '| `apps.<app>.env` | map of name → string or secret reference | `{}` |',
    );
    expect(text).toContain('| `apps.qbittorrent.vpn` | boolean | `true` |');
    expect(text).not.toContain('`apps.sonarr.port`');
  });

  it('names every app and says it is generated', () => {
    for (const def of catalog) expect(text).toContain(`\`${def.id}\``);
    expect(text).toContain('Generated by "pnpm docs:generate"');
  });
});

describe('cell', () => {
  it('keeps a table row on one line, and keeps <app> from being read as an HTML tag', () => {
    expect(cell('a | b\nby <app>.<field>')).toBe('a \\| b by \\<app>.\\<field>');
  });
});

describe('typeOf', () => {
  it.each([
    [{ type: 'boolean' }, 'boolean'],
    [{ const: 1 }, '`1`'],
    [{ type: ['string', 'number', 'boolean'] }, 'string, number or boolean'],
    [{ type: 'integer', minimum: 1, maximum: 65535 }, 'integer, 1 to 65535'],
    [{ anyOf: [{ type: 'null' }, { type: 'object' }] }, 'object'],
  ] satisfies [Schema, string][])('%j is %s', (schema, expected) => {
    expect(typeOf(schema)).toBe(expected);
  });
});
