import type { Catalog } from '@mediaplane/engine';

/** The parts of a JSON Schema the reference reads. */
export interface Schema {
  $id?: string;
  type?: string | string[];
  description?: string;
  default?: unknown;
  const?: unknown;
  enum?: unknown[];
  minimum?: number;
  maximum?: number;
  properties?: Record<string, Schema>;
  required?: string[];
  additionalProperties?: Schema | boolean;
  anyOf?: Schema[];
}

interface Row {
  field: string;
  type: string;
  default: string;
  description: string;
}

const GENERATED =
  '<!-- Generated by "pnpm docs:generate" from packages/engine/src/config/schema.ts and the catalog. Do not edit. -->';

/** { file } or { env }: shown as one type. */
function isSecretRef(schema: Schema): boolean {
  const keys = (schema.anyOf ?? []).map((option) =>
    Object.keys(option.properties ?? {}).join(),
  );
  return keys.length === 2 && keys.includes('file') && keys.includes('env');
}

/** A field's type, in words. */
export function typeOf(schema: Schema): string {
  if (schema.const !== undefined) return `\`${JSON.stringify(schema.const)}\``;
  if (schema.enum !== undefined) {
    return `one of ${schema.enum.map((value) => `\`${String(value)}\``).join(', ')}`;
  }
  if (isSecretRef(schema)) return 'secret reference';
  const options = (schema.anyOf ?? []).filter((option) => option.type !== 'null');
  if (options.length > 0) return options.map(typeOf).join(' or ');
  const types = Array.isArray(schema.type) ? schema.type : [schema.type ?? 'any'];
  if (types.length > 1)
    return `${types.slice(0, -1).join(', ')} or ${types.at(-1) ?? ''}`;
  const type = types[0] ?? 'any';
  if (type === 'integer') return integerRange(schema);
  if (type === 'object' && typeof schema.additionalProperties === 'object') {
    return `map of name → ${typeOf(schema.additionalProperties)}`;
  }
  return type;
}

function integerRange({ minimum, maximum }: Schema): string {
  if (
    minimum !== undefined &&
    maximum !== undefined &&
    maximum < Number.MAX_SAFE_INTEGER
  ) {
    return `integer, ${String(minimum)} to ${String(maximum)}`;
  }
  return minimum === undefined ? 'integer' : `integer, at least ${String(minimum)}`;
}

/** One row per field, and its fields after it. Maps and secret references are one row. */
function rows(schema: Schema, prefix: string): Row[] {
  const required = new Set(schema.required ?? []);
  return Object.entries(schema.properties ?? {}).flatMap(([name, child]) => {
    const field = prefix === '' ? name : `${prefix}.${name}`;
    const row: Row = {
      field,
      type: typeOf(child),
      default: required.has(name)
        ? 'required'
        : child.default === undefined
          ? ''
          : `\`${JSON.stringify(child.default)}\``,
      description: child.description ?? '',
    };
    return [row, ...rows(child, field)];
  });
}

/**
 * A Markdown table cell: pipes escaped, line breaks flattened, and "<" escaped, because
 * GitHub reads `<app>` as an HTML tag and drops it from the page.
 */
export const cell = (text: string) =>
  text.replaceAll('|', '\\|').replaceAll('<', '\\<').replaceAll('\n', ' ');

function table(list: readonly Row[]): string[] {
  return [
    '| Field | Type | Default | Description |',
    '| --- | --- | --- | --- |',
    ...list.map(
      (row) =>
        `| \`${row.field}\` | ${cell(row.type)} | ${cell(row.default)} | ${cell(row.description)} |`,
    ),
  ];
}

/** An app's entry under apps:, without its "or nothing" alternative. */
function entryOf(schema: Schema | undefined): Schema {
  return (schema?.anyOf ?? []).find((option) => option.type === 'object') ?? {};
}

/** docs/reference/stack-yaml.md (spec §9), from the published JSON Schema and the catalog. */
export function renderStackReference(schema: Schema, catalog: Catalog): string {
  const top = Object.fromEntries(
    Object.entries(schema.properties ?? {}).map(([name, child]): [string, Schema] => [
      name,
      // apps gets sections of its own below.
      name === 'apps' ? { ...child, properties: undefined } : child,
    ]),
  );
  const entries = schema.properties?.apps?.properties ?? {};
  const keysOf = (id: string) => Object.keys(entryOf(entries[id]).properties ?? {});
  const shared = catalog
    .map((def) => keysOf(def.id))
    .reduce((common, keys) => common.filter((key) => keys.includes(key)));
  const sharedSchema = entryOf(entries[catalog[0]?.id ?? '']);
  const sharedRows = rows(
    {
      properties: Object.fromEntries(
        shared.map((key): [string, Schema] => [
          key,
          sharedSchema.properties?.[key] ?? {},
        ]),
      ),
    },
    'apps.<app>',
  );
  const ownRows = catalog.flatMap((def) => {
    const entry = entryOf(entries[def.id]);
    const own = Object.entries(entry.properties ?? {}).filter(
      ([key]) => !shared.includes(key),
    );
    return rows({ properties: Object.fromEntries(own) }, `apps.${def.id}`);
  });
  return [
    '# `stack.yaml` reference',
    '',
    GENERATED,
    '',
    '`stack.yaml` describes the stack you want, and `mediaplane plan` and `apply` make the host match it. This page lists every field.',
    '',
    `Editors can check the file as you type against its [JSON Schema](stack.schema.json). \`mediaplane init\` writes this first line for you:`,
    '',
    '```yaml',
    `# yaml-language-server: $schema=${schema.$id ?? ''}`,
    '```',
    '',
    'A **secret reference** is `{ file: secrets/<name> }`, a file relative to the Mediaplane home, or `{ env: NAME }`, an environment variable. A secret itself never goes in `stack.yaml` ([ADR 0009](../adr/0009-no-secrets-in-stack-yaml.md)).',
    '',
    '## Fields',
    '',
    ...table(rows({ ...schema, properties: top }, '')),
    '',
    '## Settings every app takes',
    '',
    'Under `apps.<app>`, where `<app>` is one of the apps listed at the end of this page.',
    '',
    ...table(sharedRows),
    '',
    "## One app's own settings",
    '',
    ...table(ownRows),
    '',
    '## Apps',
    '',
    '| App | Id |',
    '| --- | --- |',
    ...catalog.map((def) => `| ${def.name} | \`${def.id}\` |`),
    '',
  ].join('\n');
}
