import { compare } from '../util/sort';

const HEADER = [
  '# Generated by Mediaplane. DO NOT EDIT: rewritten on every apply.',
  '# The secret values compose.yaml refers to. Keep this file private (mode 0600).',
];

/** generated/.env: the value of every ${MP_…} variable compose.yaml references. */
export function renderEnvFile(values: Record<string, string>): string {
  const lines = Object.entries(values)
    .sort(([a], [b]) => compare(a, b))
    .map(([name, value]) => `${name}=${envValue(value)}`);
  return [...HEADER, ...lines, ''].join('\n');
}

/**
 * One value in Compose's .env syntax. Single quotes keep everything literal. A value with
 * a single quote, a line break, or a trailing backslash uses double quotes instead, where
 * \ " $ and line breaks must be escaped. (A trailing backslash needs them because Compose
 * reads \' as an escaped quote even inside single quotes, so it would swallow the closing
 * quote and the next line.) Checked against Compose 5.5.1, 2026-10-09.
 */
export function envValue(value: string): string {
  if (!/['\n\r\t]|\\$/.test(value)) return `'${value}'`;
  const escaped = value
    .replaceAll('\\', '\\\\')
    .replaceAll('"', '\\"')
    .replaceAll('$', '\\$')
    .replaceAll('\n', '\\n')
    .replaceAll('\r', '\\r')
    .replaceAll('\t', '\\t');
  return `"${escaped}"`;
}
