import { describe, expect, it } from 'vitest';
import { parseEnvFile } from '../testing/fakes';
import { envValue, renderEnvFile } from './env';

describe('envValue', () => {
  it.each([
    ['plain-value', "'plain-value'"],
    ['', "''"],
    ['  spaced  ', "'  spaced  '"],
    ['$HOME ${X} "dq" # hash = eq \\back', '\'$HOME ${X} "dq" # hash = eq \\back\''],
    ["it's", '"it\'s"'],
    ['it\'s "q" $X \\b', '"it\'s \\"q\\" \\$X \\\\b"'],
    ['line1\nline2', '"line1\\nline2"'],
    ['cr\rtab\t', '"cr\\rtab\\t"'],
    // Compose reads \' as an escaped quote even inside single quotes, so a trailing
    // backslash would swallow the closing quote.
    ['abc\\', '"abc\\\\"'],
    ['\\', '"\\\\"'],
    ['say "hi"\\', '"say \\"hi\\"\\\\"'],
    ["it's abc\\", '"it\'s abc\\\\"'],
  ])('%j → %s', (value, expected) => {
    expect(envValue(value)).toBe(expected);
  });
});

describe('renderEnvFile', () => {
  it('writes a header and one sorted line per variable', () => {
    expect(
      renderEnvFile({ MP_SONARR_API_KEY: 'fake-b', MP_GLUETUN_WIREGUARD_KEY: 'fake-a' }),
    ).toBe(
      [
        '# Generated by Mediaplane. DO NOT EDIT: rewritten on every apply.',
        '# The secret values compose.yaml refers to. Keep this file private (mode 0600).',
        "MP_GLUETUN_WIREGUARD_KEY='fake-a'",
        "MP_SONARR_API_KEY='fake-b'",
        '',
      ].join('\n'),
    );
  });

  it('reads back exactly', () => {
    const values = {
      MP_A: 'it\'s "q" $X \\b',
      MP_B: 'line1\nline2\ttab\rcr',
      MP_C: '',
      MP_D: '$HOME ${X}',
      MP_E: 'abc\\',
      MP_F: 'say "hi"\\',
      MP_G: 'tail',
    };
    expect(parseEnvFile(renderEnvFile(values))).toEqual(values);
  });
});
