import { describe, expect, it } from 'vitest';
import { parse } from 'yaml';
import type { ComposeFile } from './compose';
import { composeToYaml } from './yaml';

const compose: ComposeFile = {
  name: 'mediaplane',
  services: {
    web: {
      image: 'registry.test/web:1',
      restart: 'unless-stopped',
      user: '1000:1000',
      environment: { COUNT: '1000', PASS: 'a$$b' },
      ports: ['127.0.0.1:8080:8080'],
      labels: { 'io.mediaplane.app': 'web' },
    },
  },
};
const yaml = composeToYaml(compose, '/opt/mediaplane');

describe('composeToYaml', () => {
  it('starts with the do-not-edit header', () => {
    expect(yaml.startsWith('# Generated by Mediaplane — DO NOT EDIT.')).toBe(true);
  });

  it('says how to run the stack without Mediaplane', () => {
    expect(yaml).toContain(
      '# Put your own changes in /opt/mediaplane/compose.override.yaml.',
    );
    expect(yaml).toContain(
      '#   docker compose -p mediaplane --project-directory /opt/mediaplane \\',
    );
    expect(yaml).toContain('#     --env-file /opt/mediaplane/generated/.env up -d');
  });

  it('double-quotes every port mapping and the user directive', () => {
    expect(yaml).toContain('- "127.0.0.1:8080:8080"');
    expect(yaml).toContain('user: "1000:1000"');
  });

  it('keeps numeric-looking strings as strings', () => {
    expect(yaml).toContain('COUNT: "1000"');
  });

  it('keeps escaped dollars for Compose', () => {
    expect(yaml).toContain('PASS: "a$$b"');
  });

  it('round-trips to the same data', () => {
    expect(parse(yaml)).toEqual(compose);
  });

  it('does not quote keys', () => {
    expect(yaml).toContain('\n      COUNT: "1000"');
    expect(yaml).toContain('\n      io.mediaplane.app: "web"');
  });
});

describe('composeToYaml: values that Compose would reinterpret', () => {
  const tricky: ComposeFile = {
    name: 'mediaplane',
    services: {
      web: {
        image: 'registry.test/web:1',
        restart: 'unless-stopped',
        environment: {
          BINARY: '0b101',
          DATE: '2024-01-01',
          TIMESTAMP: '2024-01-01T10:00:00Z',
          UNDERSCORE: '1_000',
        },
        labels: { 'io.mediaplane.build': '2024-01-01', 'io.mediaplane.flag': 'true' },
      },
    },
  };
  const trickyYaml = composeToYaml(tricky, '/opt/mediaplane');

  it('double-quotes every environment value', () => {
    expect(trickyYaml).toContain('UNDERSCORE: "1_000"');
    expect(trickyYaml).toContain('BINARY: "0b101"');
    expect(trickyYaml).toContain('DATE: "2024-01-01"');
    expect(trickyYaml).toContain('TIMESTAMP: "2024-01-01T10:00:00Z"');
  });

  it('double-quotes every label value', () => {
    expect(trickyYaml).toContain('io.mediaplane.build: "2024-01-01"');
    expect(trickyYaml).toContain('io.mediaplane.flag: "true"');
  });

  it('round-trips to the same data', () => {
    expect(parse(trickyYaml)).toEqual(tricky);
  });
});
