import { describe, expect, it } from 'vitest';
import { parse } from 'yaml';
import type { ComposeFile } from './compose';
import { composeToYaml } from './yaml';

const compose: ComposeFile = {
  name: 'mediaplane',
  services: {
    web: {
      image: 'registry.test/web:1',
      restart: 'unless-stopped',
      user: '1000:1000',
      environment: { COUNT: '1000', PASS: 'a$$b' },
      ports: ['127.0.0.1:8080:8080'],
      labels: { 'io.mediaplane.app': 'web' },
    },
  },
};
const yaml = composeToYaml(compose);

describe('composeToYaml', () => {
  it('starts with the do-not-edit header', () => {
    expect(yaml.startsWith('# Generated by Mediaplane — DO NOT EDIT.')).toBe(true);
  });

  it('double-quotes every port mapping and the user directive', () => {
    expect(yaml).toContain('- "127.0.0.1:8080:8080"');
    expect(yaml).toContain('user: "1000:1000"');
  });

  it('keeps numeric-looking strings as strings', () => {
    expect(yaml).toContain('COUNT: "1000"');
  });

  it('keeps escaped dollars for Compose', () => {
    expect(yaml).toContain('PASS: a$$b');
  });

  it('round-trips to the same data', () => {
    expect(parse(yaml)).toEqual(compose);
  });
});
