import { Document, isMap, isScalar, isSeq, Scalar, visit } from 'yaml';
import type { ComposeFile } from './compose';

/** Each line starts with a space so it renders as "# …". */
export const COMPOSE_HEADER = [
  ' Generated by Mediaplane — DO NOT EDIT. This file is rewritten on every apply.',
  ' Put your own changes in compose.override.yaml next to stack.yaml.',
].join('\n');

export function composeToYaml(compose: ComposeFile): string {
  const doc = new Document(compose);
  // Compose's YAML parser resolves more plain scalars than YAML 1.2 does: "80:80" is read
  // as a base-60 number, and "1_000", "0b101" and "2024-01-01" as a number or a timestamp.
  // Values are strings, so quote every one that could be user-supplied.
  visit(doc, {
    Pair(_key, pair) {
      if (!isScalar(pair.key)) return;
      if (pair.key.value === 'ports' && isSeq(pair.value)) {
        for (const item of pair.value.items) {
          if (isScalar(item)) item.type = Scalar.QUOTE_DOUBLE;
        }
      }
      if (pair.key.value === 'user' && isScalar(pair.value)) {
        pair.value.type = Scalar.QUOTE_DOUBLE;
      }
      if (
        (pair.key.value === 'environment' || pair.key.value === 'labels') &&
        isMap(pair.value)
      ) {
        for (const entry of pair.value.items) {
          if (isScalar(entry.value)) entry.value.type = Scalar.QUOTE_DOUBLE;
        }
      }
    },
  });
  doc.commentBefore = COMPOSE_HEADER;
  return doc.toString({ lineWidth: 0 });
}
