import { Document, isScalar, isSeq, Scalar, visit } from 'yaml';
import type { ComposeFile } from './compose';

/** Each line starts with a space so it renders as "# …". */
export const COMPOSE_HEADER = [
  ' Generated by Mediaplane — DO NOT EDIT. This file is rewritten on every apply.',
  ' Put your own changes in compose.override.yaml next to stack.yaml.',
].join('\n');

export function composeToYaml(compose: ComposeFile): string {
  const doc = new Document(compose);
  // Quote "a:b" values: YAML 1.1 parsers read unquoted "80:80" as a base-60 number.
  visit(doc, {
    Pair(_key, pair) {
      if (!isScalar(pair.key)) return;
      if (pair.key.value === 'ports' && isSeq(pair.value)) {
        for (const item of pair.value.items) {
          if (isScalar(item)) item.type = Scalar.QUOTE_DOUBLE;
        }
      }
      if (pair.key.value === 'user' && isScalar(pair.value)) {
        pair.value.type = Scalar.QUOTE_DOUBLE;
      }
    },
  });
  doc.commentBefore = COMPOSE_HEADER;
  return doc.toString({ lineWidth: 0 });
}
