import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { catalog } from '@mediaplane/catalog';
import { stackJsonSchema } from '@mediaplane/engine';
import { format, resolveConfig } from 'prettier';
import { withFacts } from './docs/catalog-facts';
import { renderCliReference } from './docs/cli-reference';
import { renderStackReference } from './docs/stack-reference';
import { ranAsScript, ROOT } from './root';

/**
 * Formatted as the Prettier CLI would, which reads .editorconfig too, so `pnpm lint` and
 * `pnpm docs:check` agree.
 */
export async function prettify(path: string, content: string): Promise<string> {
  const filepath = join(ROOT, path);
  const config = await resolveConfig(filepath, { editorconfig: true });
  return format(content, { ...config, filepath });
}

/** Every generated file, by path from the repository root, with its current content. */
export async function generatedFiles(): Promise<{ path: string; content: string }[]> {
  const schema = stackJsonSchema(catalog);
  const published = {
    $comment:
      'Generated by "pnpm docs:generate" from packages/engine/src/config/schema.ts and the catalog. Do not edit.',
    ...schema,
  };
  const files: { path: string; content: string }[] = [
    {
      path: 'docs/reference/stack.schema.json',
      content: `${JSON.stringify(published, null, 2)}\n`,
    },
    {
      path: 'docs/reference/stack-yaml.md',
      content: renderStackReference(schema, catalog),
    },
    { path: 'docs/reference/cli.md', content: renderCliReference() },
  ];
  for (const def of catalog) {
    const path = `catalog/${def.id}/README.md`;
    files.push({
      path,
      content: withFacts(await readFile(join(ROOT, path), 'utf8'), def, path),
    });
  }
  return Promise.all(
    files.map(async (file) => ({
      path: file.path,
      content: await prettify(file.path, file.content),
    })),
  );
}

async function main(check: boolean): Promise<number> {
  const stale: string[] = [];
  for (const { path, content } of await generatedFiles()) {
    const target = join(ROOT, path);
    const current = await readFile(target, 'utf8').catch((cause: unknown) => {
      if (cause instanceof Error && 'code' in cause && cause.code === 'ENOENT')
        return undefined;
      throw cause;
    });
    if (current === content) continue;
    if (check) {
      stale.push(path);
      continue;
    }
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, content);
    console.log(`wrote ${path}`);
  }
  if (stale.length === 0) return 0;
  console.error(
    `These generated files are out of date:\n${stale.map((p) => `  ${p}\n`).join('')}Run "pnpm docs:generate" and commit the result.`,
  );
  return 1;
}

if (ranAsScript(import.meta.url, process.argv[1])) {
  process.exitCode = await main(process.argv.includes('--check'));
}
